### ISSUE TITLE
lein-clojuredocs 1.0.2 fails on tools.nrepl 0.2.2

### ISSUE THREAD

**Issue by jafingerhut** [dakrone/lein-clojuredocs#2]
Steps to reproduce:

<pre>
% git clone git://github.com/clojure/tools.nrepl.git
% cd tools.nrepl
% git checkout tools.nrepl-0.2.2
% cat project.clj
(defproject clojure.tools.nrepl "0.2.2"
  :description "tools.nrepl 0.2.2"
  :eval-in :leiningen
  :source-paths [ "src/main/clojure" ])

% lein clojuredocs
</pre>

Below is the output I saw, with the stack trace truncated.  I didn't see anything directly lein-clojuredocs related in the portion of the stacktrace I've removed:

<pre>
+ lein clojuredocs
[+] Processing clojure.tools.nrepl...
[+] Processing clojure.tools.nrepl.ack...
[+] Processing clojure.tools.nrepl.bencode...
[+] Processing clojure.tools.nrepl.cmdline...
[+] Processing clojure.tools.nrepl.helpers...
[+] Processing clojure.tools.nrepl.middleware...
[+] Processing clojure.tools.nrepl.middleware.interruptible-eval...
[+] Processing clojure.tools.nrepl.middleware.load-file...
[+] Processing clojure.tools.nrepl.middleware.pr-values...
[+] Processing clojure.tools.nrepl.middleware.session...
[+] Processing clojure.tools.nrepl.misc...
[+] Processing clojure.tools.nrepl.server...
[+] Processing clojure.tools.nrepl.transport...
[-] Writing output to clojure.tools.nrepl-0.2.2.json.gz
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class clojure.lang.Var: #'clojure.tools.nrepl.middleware.pr-values/pr-values
    at cheshire.generate$generate$fn__7788.invoke(generate.clj:122)
    at cheshire.generate$generate.invoke(generate.clj:122)
    at cheshire.generate$generate.invoke(generate.clj:93)
    at cheshire.generate$generate.invoke(generate.clj:89)
    at cheshire.generate$generate.invoke(generate.clj:89
    at cheshire.generate$generate.invoke(generate.clj:97)
    at cheshire.generate$generate.invoke(generate.clj:89)
    at cheshire.generate$generate.invoke(generate.clj:89)
    at cheshire.core$generate_string.invoke(core.clj:31)
    at cheshire.core$generate_string.invoke(core.clj:19)
    at cadastre.analyzer$serialize_project_info.doInvoke(analyzer.clj:111)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at cadastre.analyzer$gen_project_docs_json.doInvoke(analyzer.clj:179)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at user$eval466.invoke(NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6609)
    at clojure.lang.Compiler.eval(Compiler.java:6582)
</pre>

**Comment by dakrone** [comment]
Interesting, I'll check it out, thanks for the report!
